matrix:
  include:
    ############################# IOS BUILD #############################
    - if: (branch = master OR branch = dev) AND type = push
      os: osx
      language: objective-c
      osx_image: xcode8.3

      env:
        global:
          - JOBS=1

      before_install:
        - sh scripts/before-install-osx.sh

      script:
        - sh scripts/build-ios.sh

      deploy:
        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs-dev
          local-dir: cordova/platforms/ios/build
          upload-dir: ios-build
          acl: public_read
          verbose: true
          on:
            branch: dev
            condition: $TRAVIS_OS_NAME = osx

        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs
          local-dir: cordova/platforms/ios/build
          upload-dir: ios-build
          acl: public_read
          verbose: true
          on:
            branch: master
            condition: $TRAVIS_OS_NAME = osx

    ############################# ANDROID BUILD #############################
    - if: (branch = master OR branch = dev) AND type = push
      os: linux
      sudo: required
      language: android
      android:
        components:
          - tools
          - tools
          - platform-tools
          - build-tools-26.0.1
          - android-26
      addons:
        apt:
          sources:
            - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
              key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
            - yarn
            # - jq
      licenses:
        - android-googletv-license-.+
        - google-gdk-license-.+
        - android-sdk-license-.+
        - intel-android-extra-license-.+
        - android-sdk-preview-license-.+
        - mips-android-sysimage-license-.+

      env:
        global:
        - JOBS=1
        - JAVA_HOME=/usr/lib/jvm/java-8-oracle

      cache:
        directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/Library/Caches/Yarn/v1/
        - $HOME/.cache/yarn/v1/

      before_install:
        - export LANG=en_US.UTF-8
        - sh scripts/before-install-linux.sh

      script:
        - sh scripts/build-android.sh

      deploy:
        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs-dev
          local-dir: cordova/platforms/android/build
          upload-dir: android-build
          acl: public_read
          verbose: true
          on:
            branch: dev
            condition: $TRAVIS_OS_NAME = linux

        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs
          local-dir: cordova/platforms/android/build
          upload-dir: android-build
          acl: public_read
          verbose: true
          on:
            branch: master
            condition: $TRAVIS_OS_NAME = linux

    ############################# EMBER BUILD #############################
    - language: node_js
      node_js:
        - "6"

      sudo: false
      dist: trusty

      addons:
        chrome: stable

      cache:
        directories:
          - $HOME/.npm

      env:
        global:
          - JOBS=1

      before_install:
        - npm config set spin false
        - npm install -g bower

      install:
        - npm install
        - bower install

      after_success:
        - sh scripts/build-ember-app.sh

      deploy:
        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs-dev
          local-dir: dist
          acl: public_read
          verbose: true
          on:
            branch: dev

        - skip_cleanup: true
          provider: s3
          access_key_id: AKIAJMH545S5JKUIND7A
          secret_access_key:
            secure: Pd2BuDHdn1jxsfOdcfAl/ZIcCJRFT0cULG7eCaLdh0/mkaG9nbfc6+Nm3vk0S0evwHp2yPljzndia3MgepkeXfiYPjTvPvfDT6oKp2UZAUCS9SYWWxEkHyockRigDPEIJqGTg3uTBLQaxHaRSCz2SUL+QYInjo517yJrlVC5IjqhH95Zw7sgeYP2IYbKab5rY4BA2KfxDuAXDFMJPrXejT4rElnRipht1pCree/aA9cDxi48cN2VhZLicb/kI75PSNg3T7PTXfhOxhNpyCxN+wgJ0e6zFTZSW7XKYGVYeJvG1g8YSh/QCNrIx1tPcnyW59yMXNCGhqGoYRJu4Voa5ftbzI9TxlpaoXnyQ1MoKkPN3LV+DMtpXmTTraqw6bTlgrzKDTccQLwDE3g8GYNLNHpWUsSPvph5skaDOcowFrvv91OS5pvN7V0Yk0kDqMACB69gHC/b05Tb2dJlMRVmKfJUJ9HuaIdhA/a5oMzipsUnHkGYlIczHlZeqEimiLE0DGR4I6sjo+nnAVKAaGxfUJ+d/zfCjie7p8cezCeQksnVHMiaUakwIEe/b9G9Hw29xil7FU6ZLKaMCv31M2Bjdu8dumaAbeRw4gdnUhAUO1rqcPFMyJ4ldTMHJY/pJj7jAUF24vIehH/m98POBftYXhK5g2XhAELdqCBeJJjAog0=
          bucket: waldojobs
          local-dir: dist
          acl: public_read
          verbose: true
          on:
            branch: master
